- Cargo.toml
- build.rs
- src/bin/cosmogony.rs
- src/cosmogony.rs
- src/lib.rs
- src/zone.rs
- tests/cosmogony_lux_test.rs
Note that zones without boundary are currently ignored in the result.
A single test is implemented to check the number of zones per admin_level in a sample .osm.pbf.
> Implement admin_level counts, Add first test

- src/bin/cosmogony.rs
- src/cosmogony.rs
- src/lib.rs
- src/zone.rs
- tests/cosmogony_lux_test.rs
When only working on the metadata, it allows to save some time and a lot of memory.
For instance, for France, the read time goes down from 8 minutes to 2, and the memory usage from 2,6Gb down to 200Mb
> Allow to skip the geometries

- Cargo.lock
- Cargo.toml
- src/cosmogony.rs
- src/hierarchy_builder.rs
- src/lib.rs
- src/zone.rs
This defines a new function `build_hierarchy`.  
Zones are first inserted into a RTree, to look efficiently for potential parents.
In this version, the parent is required to have a lower `admin_level` ; we are not using `admin_type` yet. The parent is represented in each `Zone` object as a new `ZoneIndex` struct, and is serialized as an integer in [0, nb_zones).
Note that the  `contains` method is defined using [a custom GEOS binding](https://github.com/amatissart/rust-geos), that might be unstable at this stage.
> Implement zones containment

- Cargo.lock
- Cargo.toml
- src/bin/cosmogony.rs
- src/lib.rs
- src/zone.rs
remove mimir dependency, this way we will be able to use cosmogony in mimir easily
Do not merge this PR yet, we need https://github.com/QwantResearch/osm_boundaries_utils_rs/pull/1 to be merged first (and then the Cargo.toml needs to be updated)
> remove mimir dependency

- Cargo.lock
- Cargo.toml
- src/cosmogony.rs
- src/lib.rs
- src/zone.rs
- tests/cosmogony_lux_test.rs
the deserialization is needed by mimir to load a cosmogony.json
also reexport the main types for ergonomics.
In this Pr we override osmpbfreadeer because it needs https://github.com/TeXitoi/osmpbfreader-rs/pull/13
> Add cosmogony deserialization

- src/hierarchy_builder.rs
- src/lib.rs
- src/mutable_slice.rs
- src/zone.rs
- tests/cosmogony_lux_test.rs
add a nicely formated label to the zones
This label is inspired from [opencage formatting](https://blog.opencagedata.com/post/99059889253/good-looking-addresses-solving-the-berlin-berlin) and from the [mimirsbrunn](https://github.com/CanalTP/mimirsbrunn) zip code formatting
example of zone's label:
`Paris (75000-75116), Île-de-France, France`
`Paris 16e Arrondissement (75016-75116), Paris, Île-de-France, France`
also changed to way the osm_id were build to add the osm_type on them
so now instead of `2171347` we'll get `relation:2171347` (and maybe later `node` or `way`)
> add a human readable label

- .gitmodules
- src/zone_typer.rs
read `contained_by` and `id` libpostal's overrides (but does not yet implement the uses of those overrides, that will be for another PR.
also update libpostal's submodule to use our own fork with some correction in the yaml files (we'll be able to return to the main libpostal repository once https://github.com/openvenues/libpostal/pull/348 is merged and we have done a PR like https://github.com/osm-without-borders/libpostal/pull/1)
>  read libpostal overrides

- src/hierarchy_builder.rs
- src/lib.rs
- src/zone_typer.rs
- tests/cosmogony_lux_test.rs
Implement LibPostal overrides for the zone type.
There is 2 libpostal kind of overrides:
* override by id:
for a given `osm_id` (we only handles relations for the moment), there is an explicit type
eg:
```yaml
overrides:
id:
relation:
"42": "city_district"
```
the relation '42' will have the `city_district` type whatever it's admin_level
* override for some 'child':
All zones contained by another zone have a custom set of rules.
eg:
```yaml
overrides:
contained_by:
relation:
"42":
admin_level:
"9": "city_district"
"10": "suburb""
```
All zones contained by the zone with '42' as osm_id will have a special set of rules for their admin_level mapping.
Since to apply those rules we need to know the inclusions and to create the hierarchy we need the zone_type (to ensure some coherence) we had …
> implement libpostal overrides

- src/lib.rs
- tests/cosmogony_lux_test.rs
we don't want to keep zone's without zone_type (but the zone_type could
be ZoneType::NonAdministrative)
This way we'll for example remove the admin_level 7 in france that are
not associated to a zone_type and that are often dupplicates
WARNING: this PR introduce quite a trick
this removal invalidates the different zones indexes  (we can no longer lookup a Zone by it's id in the zones's vector)
I think it will be nice to find a nicer solution latern but for the moment it will do
> Remove untaged zones

- src/country_finder.rs
- src/lib.rs
- src/zone.rs
- src/zone_typer.rs
This is also only a performance improvement, no features added.
The zone's typing was taking quite a long time compared to what is really done.
Is was primarily because we need to find the country of a zone to be able to find the right libpostal rule.
This was done by looking in a Countries  rtree (so doing some geometric contains which is quite costly).
We now only use the inclusion vector (computed as the begining of the run), so it's way more efficient.
The zone typing is also now done in parallele (the code is a big less clear now, so we need to see if it's worth it)
Note: with this the cosmogony in france takes 23mn (and output is the same as master)
> Improve the zone's zone typer performance

- .dockerignore
- Dockerfile
this way we'll be able to do
`docker run cosmogony -h`
This will make it possible to add an automated docker hub build
> add a docker file

- Cargo.lock
- Cargo.toml
- README.md
- src/hierarchy_builder.rs
- src/utils.rs
- src/zone.rs
- tests/cosmogony_lux_test.rs
A new `bbox` field is part of the `Zone` struct and is serialized in the output file.  
The output format follows GeoJson specification ("bbox" is an array of 4 floats : `[xmin, ymin, xmax, ymax]`), although it is not nested in the `geometry` object to ease the serialization/deserialization process.
Note that this PR includes some refactoring in tests/ to run similar checks with and without serialization of the cosmogony output.
> Add a `bbox` in zones output

- src/bin/cosmogony.rs
* Use serde_json::to_writer to skip the serialization in RAM
* Wrap the file in a BufWriter to avoid buffering issues
> Direct serialization to output file

- taginfo.json
Taginfo is a very useful project to learn about tags in OSM, and you can use it to know what the tags are used to.
this PR add a taginfo file for our project, so it can be displayed in the pages for the tags we use.
The documentation for the file format can be found here : https://wiki.openstreetmap.org/wiki/Taginfo/Projects
I didn't add all the tags we use in here, because this does not have to replace our documentation, it is mainly a way to advertise our project and how to map in OSM to use it ;)
> add taginfo file to let OSMers know which tags we use

- .travis.yml
- Cargo.lock
- Cargo.toml
* Diff from 0.3.2: https://github.com/osm-without-borders/cosmogony/compare/4cf842a0f2b0ed6b66e308ee18a23319a3b6954e...amatissart:bump-version
* Update travis script to run `cargo publish` on the corresponding git tag
> Bump version to 0.3.3

- src/zone.rs
- tests/cosmogony_lux_test.rs
The current regex matches all tags `*name:*` and keep the last one from the tags list for each language. As a consequence the i18n labels may actually contain the "official_name" (or potentially any other name).
I don't think that is expected. This PR updates the regex to match only tags **starting** with `name:`
> Fix i18n labels to match "name:*" tags only

- .travis.yml
- README.md
- src/cosmogony.rs
- src/country_finder.rs
- src/hierarchy_builder.rs
- src/lib.rs
- src/zone.rs
- src/zone_typer.rs
- tests/cosmogony_lux_test.rs
* Complete tags with names from **"label"** node (if present) on all zones
* Complete tags with names from **"admin_center"** node (only for cities, or admin_center nodes with the same "wikidata" id as the relation.
Misc
* Use stable "cargo fmt"
* Minor changes, following clippy recommendations
> Read extra names from "label" or "admin_center" nodes

- Cargo.lock
- Cargo.toml
- src/bin/cosmogony.rs
- src/cosmogony.rs
- src/file_format.rs
- src/lib.rs
- src/zone.rs
- tests/cosmogony_lux_test.rs
add the possibility to dump json stream file
naming the ouput file "*.jsonl" (or ".jsonl.gz") will dump the cosmogony file as jsons stream, each line being a zone as json.
it makes it way ligher to read the file (it's not mandatory to load the whole file in memory).
For easier cosmogony use, several reading methods have been provided:
* `load_cosmogony_from_file` -> deduce the file format from extension and load the whole cosmogony
* `read_zones_from_file` -> decude the file format and return an iterator on the zones
* `read_zones`: stream zones from a buffered reader. Can be a bit more efficient if the cosmogony format is known.
>  add new output format

- Cargo.toml
- cosmogony/Cargo.toml
Update zones classification via libpostal:
* Cities in Netherlands (https://github.com/osm-without-borders/libpostal/pull/11)
* Cities in Portugal (https://github.com/osm-without-borders/libpostal/pull/12)
> v0.7.1: update libpostal configuration

- cosmogony/src/file_format.rs
`an_array.into_iter()` currently just works because of the autoref
feature, which then calls `<[T] as IntoIterator>::into_iter`. But
in the future, arrays will implement `IntoIterator`, too. In order
to avoid problems in the future, the call is replaced by `iter()`
which is shorter and more explicit.
A crater run showed that your crate is affected by a potential future 
change. See https://github.com/rust-lang/rust/pull/65819 for more information.
> Use `slice::iter` instead of `into_iter` to avoid future breakage

- Cargo.lock
- Cargo.toml
- cosmogony/Cargo.toml
* Apply https://github.com/osm-without-borders/libpostal/pull/13
* Update dependencies (via `cargo update`)
> v0.7.2: Update libpostal and dependencies

- Cargo.lock
- Cargo.toml
This dependency on `ordered_floats` prevent `cargo install`. 
Yet, it can easily be removed without a noticeable effect (build or test)
> Remove dependency on ordered float

- src/zone_ext.rs
- tests/cosmogony_test.rs
* **population**  
Administrative relations in OSM data often lack the `population` tag, whereas it's often present on _label_ nodes. This tag can notably be used as a weight value, and using the _label_ node is more reliable than the value that may be contained in the _admin_centre_ tags.   
This PR includes the `population` tag from the label node into the zone `tags`, using the existing behavior used for `name:*` tags.
* **names**
#72 implemented the import of name values from the _admin_centre_ tags for cities.  
In practice, this caused some rare issues for cities where the admin centre still represent a former administrative entity which is no longer considered as a city, for example after a merger of "communes" in France.  
This PR ignores names values from this _admin_centre_ node …
> Improvements about how tags from "label" and "center" nodes are used as fallback values

- cosmogony/src/zone.rs
This isn't critical but it could invite to use more `HashMap` and `HashSet` which are supposingly more efficient that their `BTree` equivalents.
> zone: implement `Hash` for enum types

- Cargo.lock
- Cargo.toml
- cosmogony/Cargo.toml
- cosmogony/src/zone.rs
- src/zone_ext.rs
- src/zone_typer.rs
- tests/cosmogony_test.rs
Update dependencies, notably:
* geo 0.15, to fix numerical instability in centroid calculation
* osm_boundaries_utils 0.8, to include https://github.com/QwantResearch/osm_boundaries_utils_rs/pull/12
* osmpbfreader 0.14, using `smartstring` in `Tags` objects.
> Update dependencies, including geo 0.15 to fix numerical instability

- .travis.yml
- Dockerfile
Debian 9 “Stretch” is now LTS: https://wiki.debian.org/LTS
And the [base docker images for Rust](https://hub.docker.com/_/rust) based on it are no longer updated with recent Rust versions.
> Upgrade docker image from Debian 9 (stretch) to 10 (buster)

- Cargo.lock
- Cargo.toml
- src/additional_zones.rs
After Voronoi diagrams are built, the resulted boundaries need to be processed so that they don't overlap official boundaries defined in OSM. The current implementation of `additional_zones.rs` uses multiple `Vec` to store `Zone` and `Geometry` objects that are used to compute a geometry difference, using the Geos library.
The implementation does not ensure that the map `z_idx_to_place_idx` used to make the link between these vectors contains correct indices. Zones for which the Geos conversion fails could cause a shift in this index.
This PR suggests to replace this mechanism with a new shared struct `GeosBoundaryCache` that is in charge of storing the Geos boundaries, indexed with explicit `ZoneIndex` values. It should be less error-prone, and possibly more performant as cities …
> Replace precomputing of Geos geometries with shared cache, and upgrade dependencies

- src/bin/cosmogony.rs
- tests/cosmogony_test.rs
In .travis.yml, `cargo run -- --version` is used to extract the current package version.  
But #106 introduced a small issue, that caused the `--version` command to be executed twice.
This PR should fix the issue, and adds a test to ensure the version is correctly returned.
> Fix publish script and test --version command

- cosmogony/src/zone.rs
- src/lib.rs
- src/zone_ext.rs
- tests/cosmogony_test.rs
I'm trying to build region polygons for nearly all of the countries in the world, but I need separate per-country output (i.e. easily group all zones of a given country).
I was originally doing this by having a list of country codes and indexing into the [Geofabrik index](https://download.geofabrik.de/index-v1-nogeom.json) to obtain the specific country's PBF extract. However, some country codes are entirely missing from the Geofabrik index, such as `ae` which I believe is in the catch-all [GCC States](https://download.geofabrik.de/asia/gcc-states.html) extract.
That's something I can manually fix by adding my own index entries locally, but it makes me think that maybe I should just be running Cosmogony against the entire planet PBF. The only wrinkle in this is that in order to get …
> Add and populate Zone.country_code field

- Cargo.lock
- cosmogony/src/zone.rs
- src/additional_zones.rs
- src/zone_ext.rs
This PR fixes 2 inconsistencies about additional cities boundaries, based on Voronoi polygons:
- City points are no longer associated with parent Admins whose type is smaller than `City`.  
This should fix cases where nodes with `place=city` were wrongly ignored as they were contained into a `CityDistrict` or a `Suburb`.
- During the "subtracting step" that cleans up the Voronoi diagram to take into account other pre-existing polygons, all Admins with the same parent are also considered, in addition to the nearby `City` zones. This should fix cases where generated boundaries could cover several `CountryRegion`, `State` or  `StateDistrict` (that could potentially be associated with their own Voronoi diagram, resulting in overlapping cities).
Other changes are mostly optimizations, and code …
> Fix additional cities hierarchy

- src/additional_zones.rs
It runs faster for 2 reasons:
* the intersection check is parallelized, instead of running in a potentially very long loop
* filtering early in `get_zones_to_subtract` may avoid unnecessary and expensive geometry conversions (with `geos::Geometry::try_from`)  in `subtract_existing_zones`.
> additional_zones: optimization for zones subtractions

- Cargo.lock
- Cargo.toml
- cosmogony/Cargo.toml
- cosmogony/src/read.rs
This will be useful for the ongoing integration of ES7 in "mimisrbrunn", that attempts to build a thread-safe `futures::stream::Stream`.
> Ensure that the iterator returned by `read_zones_from_file` is Send + Sync

- .github/workflows/docker.yml
The docker image is pushed to Github Container Registry (https://ghcr.io).  
The login uses the `GITHUB_TOKEN` provided automatically during the workflow run.  
See https://docs.github.com/en/actions/reference/authentication-in-a-workflow for more details.
> Build docker image in a github workflow

- .github/workflows/test-and-publish.yml
`cargo run -- --version` needs to be executed in the root folder :sweat_smile:
> workflow: fix cargo publish

- Cargo.lock
- Cargo.toml
- cosmogony/Cargo.toml
- cosmogony/src/file_format.rs
- cosmogony/src/read.rs
- cosmogony/src/zone.rs
- src/additional_zones.rs
- src/bin/cosmogony.rs
- src/country_finder.rs
- src/hierarchy_builder.rs
- src/lib.rs
- src/merger.rs
- src/zone_ext.rs
- src/zone_typer.rs
As a contribution of sanitizing dependencies in mimir's ecosystem:
- replace unmaintained `failure` crate with `anyhow` (they basically do the same job of "I don't want any fined-grained error management)
- cargo update and manually update outdated pinned dependancies
- update to Rust 2021 & fix clippy lints
> Update outdated depedencies :latin_cross: 

- Cargo.toml
- Dockerfile
The new [1.57](https://blog.rust-lang.org/2021/12/02/Rust-1.57.0.html) version of Rust allows to create profiles different than `debug` and `release`.
As cosmogony is very heavy on CPU I think we should enable aggressive compile-time optimizations, and this new cargo feature allows to do it at basically no cost.
We will have to wait until the docker images for x86_64 are updated before we merge this though :grimacing:
> add production profile with aggressive link time optimizations

- Cargo.lock
- Cargo.toml
- src/bin/cosmogony.rs
- src/country_finder.rs
- src/zone_ext.rs
- src/zone_typer.rs
Structopt is now in maintenance mode as all its features have been stabilized in clap, so no need for fragmentation here: https://github.com/TeXitoi/structopt#maintenance.
Also fixes a few clippy lints.
> Use clap instead of structopt

- src/bin/cosmogony.rs
This should help orchestration with argo, which is currently painful as you can't easily generate advanced parameter structures.
> allow filter-langs parameter to contain comma-separated values

- Cargo.toml
- src/lib.rs
We are doing unbuffered I/O while reading the input file, which can lead leads to very slow computation on some environments (in our case PVCs in a kube clusters). I didn't dig into specific details but I saw that osmpbfreader doesn't wrap the reader with a buffer and makes atomic reads which would lead to an I/O operation each (often just a u32).
> add a buffer arround input file

- .github/workflows/test-and-publish.yml
- Dockerfile
- cosmogony/src/read.rs
- cosmogony/src/zone.rs
- src/additional_zones.rs
- src/lib.rs
- src/zone_ext.rs
- tests/cosmogony_test.rs
Some suburbs are not imported, when they are attached to a node and not a relation.
This PR mainly changes the filter `is_place` to add suburbs together with towns and villages, and fixes a few things that were not general enough to support this change.
> Add missing suburbs
